package:
  name: openjpeg
  version: 2.1.0

source:
    url: https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz
    fn: openjpeg-2.1.tar.gz

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
    - libpng
    - libtiff
  run:
      - libtiff
      - libpng
      - zlib
