# Recipe needed to add nose as a test requirement (no idea which dependency
# actually needs nose...healpy does not).
about:
  home: http://github.com/healpy
  license: GNU General Public License v2 or later (GPLv2+)
  summary: Healpix tools package for Python
package:
  name: healpy
  version: {{version}}
source:
  fn: healpy-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/h/healpy/healpy-{{version}}.tar.gz
requirements:
  build:
  - python
  - setuptools
  - matplotlib
  - numpy x.x
  - six
  - astropy
  run:
  - python
  - matplotlib
  - numpy x.x
  - six
  - astropy

test:
  imports:
  - healpy
  - healpy.test
  requires:
  - pytest
  - nose
